# generate the supplementary tables
devtools::load_all ('..', export_all=F)
#library (tidyverse)

root_dir <- '/mnt/c/Users/Yutong/Documents/bioinformatics/reproduction/'
root <- paste (root_dir, 'results/', sep='/')
merge_dir <- paste (root, 'XLYBPZ_Dylan_dir', sep='/')
x <- load (paste (merge_dir, 'final_merged_tb.Robj', sep='/') )
all_data <- get (x)

# table S1: cluster assignment
save_dir1 <- paste (root, 'manuscript/figure1', sep='/')
in_vivo <- all_data [, all_data$date != 'in_vitro']
table (in_vivo$assigned_cluster, in_vivo$broad_type) %>% 
        write.csv (paste (save_dir1, 'TableS1.csv', sep='/'))

# table S2: DE genes
save_DE_genes (in_vivo, save_dir1, group.by='broad_type', label='all_vivo')
library (org.Hs.eg.db)
save_DE_genes (all_data, save_dir1, group.by='broad_type', label='all',
               show_num='all', save_format='gene_table',
               organism_db=org.Hs.eg.db)

# table S3: WGCNA genes (automatically generated by figure S3)
sup_save_dir2 <- paste (root, 'manuscript/figureS2', sep='/')
color_row <- read.csv ( paste ( sup_save_dir2, 'WGCNA/module_genes.csv' , sep='/'), row.names=1)
WG <- modules::use ('WGCNA_utils.R')
colnames (color_row) <- WG$colors2labels (colnames (color_row), prefix='GC')
write.csv (color_row, paste (save_dir1, 'TableS3.csv', sep='/'), row.names=F )

# table S4
show_data <- all_data@meta.data [!is.na (all_data$MGP_PT) & !all_data$broad_type %in% c('EPI', 'PE'),]
vivo_cells <- unique (as.character (all_data$assigned_cluster))
vivo_cells <- vivo_cells [!vivo_cells %in% ML$in_vitro_cells]
all_cells <- c(vivo_cells, 'hESC', 'hESC_YAN', 'hTSC_OKAE', 'hTSC_TURCO')

show_data %>% select ( all_of (c(all_cells, 'assigned_cluster') ) ) %>%
        filter (assigned_cluster %in% vivo_cells) %>%
        gather ( 'cell_type', 'prob', -assigned_cluster) %>%
        group_by (assigned_cluster, cell_type ) %>%
        summarise (max_prob = max (prob) ) %>%
        magrittr::set_colnames (c('reference', 'compare', 'max_prob')) %>%
        as.data.frame () %>%
        mutate (compare = ML$partial_relevel (compare, ML$cell_orde) ) %>%
        spread (compare, max_prob) %>%
        write.csv (paste (save_dir1, 'TableS4.csv', sep='/'), row.names=F)

# table ?
# save DE genes with cell types as columns
library (org.Hs.eg.db)
devtools::load_all ('..', export_all=F)
save_DE_genes (in_vivo, save_dir1, group.by='broad_type', label='all_vivo',
               save_format='gene_table', show_num='all', organism_db=org.Hs.eg.db)

save_DE_genes (all_data, save_dir1, group.by='broad_type', label='all',
               save_format='gene_table', show_num='all', organism_db=org.Hs.eg.db)
